### ISSUE TITLE
更简单直接的 S3 附件上传插件

### ISSUE THREAD

**Issue by zgq354** [0xffff-one/flarum-0x#18]
由于期望本站的附件都放在对象存储服务（类 Amazon S3，目前是用腾讯云），避免服务器维护文件下载的开销。
fof/upload 插件存在一些问题会影响它的体验：

核心问题：依赖 php 透传上传下载，服务器多一层带宽压力
1. 上传不直接走 cos
2. 下载普通附件时也从主站透传

期望实现：
可以直接在浏览器直连对象存储上传文件，获得最大带宽使用效率，且无严格文件大小限制，并能用上云服务提供的图片处理的功能。

其他细节问题（低优先级）：
1. 上传的文件名会自动加上时间戳前缀 /，下载时导致文件名变长
2. 不支持签名鉴权下载文件
3. 图片附件会直接生成特定域名的 URL，并通过编辑器写入帖子内（可能会导致一些历史包袱

_Originally posted by @zgq354 in https://github.com/0xffff-one/0xffff-flarum/issues/15#issuecomment-826994215_

**Comment by stimw** [comment]
本来和对象存储内网流量不要钱...web直连的话又要收费了，香港流量还很贵

**Comment by zgq354** [comment]
想了想这块可以暂时不急着开新插件，先用旧插件搞着，只支持图片，后续再慢慢迁移

**Comment by zgq354** [comment]
先暂时 close 掉，后续再安排
